// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2_6FMUFQfXnidjAuWPCGCTXGDPV9_16I',
    appId: '1:813813682916:web:a4b2ccbec43cd34dafd2f1',
    messagingSenderId: '813813682916',
    projectId: 'lonewolf-67cb0',
    authDomain: 'lonewolf-67cb0.firebaseapp.com',
    storageBucket: 'lonewolf-67cb0.appspot.com',
    measurementId: 'G-GH0NC6F91H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVPAyDDmv3dd48r3a_-rEIT2RRxnnezIg',
    appId: '1:813813682916:android:8c631a51c3c95f0fafd2f1',
    messagingSenderId: '813813682916',
    projectId: 'lonewolf-67cb0',
    storageBucket: 'lonewolf-67cb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOCFDW3brJ8Gls3Egua8Ykk7Y89bL55KA',
    appId: '1:813813682916:ios:d3e42db4a8b58ba5afd2f1',
    messagingSenderId: '813813682916',
    projectId: 'lonewolf-67cb0',
    storageBucket: 'lonewolf-67cb0.appspot.com',
    iosBundleId: 'com.lonewolf.lonewolf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2_6FMUFQfXnidjAuWPCGCTXGDPV9_16I',
    appId: '1:813813682916:web:03fc4b66272625a4afd2f1',
    messagingSenderId: '813813682916',
    projectId: 'lonewolf-67cb0',
    authDomain: 'lonewolf-67cb0.firebaseapp.com',
    storageBucket: 'lonewolf-67cb0.appspot.com',
    measurementId: 'G-BV8GRCN86F',
  );
}
